# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TwaBWumz6yo-3G175fdEjpgCM44IVph
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(x)
plt.figure(figsize=(8, 5))
plt.plot(x, y, label='y = sin(x)', color='blue')
plt.title("Sinus funksiyasining grafigi")
plt.xlabel("x (radianlarda)")
plt.ylabel("y")
plt.grid(True)
plt.axhline(0, color='green', linewidth=0.5)
plt.axvline(0, color='green', linewidth=0.5)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(x)


num_points = 150
random_x = np.random.uniform(0, 2 * np.pi, num_points)
random_y = np.random.uniform(-1.5, 1.5, num_points)

plt.figure(figsize=(8,5)
plt.scatter(random_x, random_y, color='red', label='Tasodifiy nuqtalar')
plt.title(" Tasodifiy nuqtalar")
plt.xlabel("x (radianlarda)")
plt.ylabel("y")
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.legend()
plt.show()